In [1]:
import pandas as pd
import tensorflow as tf
from keras.layers import Dense
from keras.models import Sequential
print('relevant layers imported')

/home/bishal/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/bishal/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/home/bishal/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
Using TensorFlow backend.

relevant layers imported

In [2]:
data = pd.read_csv('../CICDataSet-TOR/CSV/Scenario-A/SelectedFeatures-10s-TOR-NonTOR.csv')

/home/bishal/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data

,Source IP,Source Port,Destination IP,Destination Port,Protocol,Flow Duration,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,...,Bwd IAT Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,label
0,10.0.2.15,53913,216.58.208.46,80,6,435,0,4597.7,435.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
1,10.0.2.15,53913,216.58.208.46,80,6,259,0,7722.01,259.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
2,10.0.2.15,53913,216.58.208.46,80,6,891,0,2244.67,891.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
3,10.0.2.15,53913,216.58.208.46,80,6,1074,0,1862.2,1074.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
4,10.0.2.15,53913,216.58.208.46,80,6,315,0,6349.21,315.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67829,131.202.240.183,7116,239.255.255.250,1900,17,0,Infinity,Infinity,0.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
67830,131.202.240.183,7116,239.255.255.250,1900,17,0,Infinity,Infinity,0.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
67831,131.202.240.87,11365,31.13.73.1,443,6,0,Infinity,Infinity,0.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
67832,131.202.6.26,13000,131.202.240.87,64584,6,0,NaN,Infinity,0.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR
67833,38.124.168.119,80,131.202.240.87,65089,6,0,NaN,Infinity,0.0,0.0,...,0,0,0,0,0,0,0,0,0,nonTOR

In [4]:
data = data.drop(['Source IP', ' Destination IP'], axis=1)

In [5]:
data

,Source Port,Destination Port,Protocol,Flow Duration,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,...,Bwd IAT Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,label
0,53913,80,6,435,0,4597.7,435.0,0.0,435,435,...,0,0,0,0,0,0,0,0,0,nonTOR
1,53913,80,6,259,0,7722.01,259.0,0.0,259,259,...,0,0,0,0,0,0,0,0,0,nonTOR
2,53913,80,6,891,0,2244.67,891.0,0.0,891,891,...,0,0,0,0,0,0,0,0,0,nonTOR
3,53913,80,6,1074,0,1862.2,1074.0,0.0,1074,1074,...,0,0,0,0,0,0,0,0,0,nonTOR
4,53913,80,6,315,0,6349.21,315.0,0.0,315,315,...,0,0,0,0,0,0,0,0,0,nonTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67829,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67830,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67831,11365,443,6,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67832,13000,64584,6,0,NaN,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67833,80,65089,6,0,NaN,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR

In [6]:
column_name = list(data.columns)

In [7]:
column_name

[' Source Port',
 ' Destination Port',
 ' Protocol',
 ' Flow Duration',
 ' Flow Bytes/s',
 ' Flow Packets/s',
 ' Flow IAT Mean',
 ' Flow IAT Std',
 ' Flow IAT Max',
 ' Flow IAT Min',
 'Fwd IAT Mean',
 ' Fwd IAT Std',
 ' Fwd IAT Max',
 ' Fwd IAT Min',
 'Bwd IAT Mean',
 ' Bwd IAT Std',
 ' Bwd IAT Max',
 ' Bwd IAT Min',
 'Active Mean',
 ' Active Std',
 ' Active Max',
 ' Active Min',
 'Idle Mean',
 ' Idle Std',
 ' Idle Max',
 ' Idle Min',
 'label']

In [8]:
data.shape

(67834, 27)

In [9]:
data = data.dropna()

In [10]:
data

,Source Port,Destination Port,Protocol,Flow Duration,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,...,Bwd IAT Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,label
0,53913,80,6,435,0,4597.7,435.0,0.0,435,435,...,0,0,0,0,0,0,0,0,0,nonTOR
1,53913,80,6,259,0,7722.01,259.0,0.0,259,259,...,0,0,0,0,0,0,0,0,0,nonTOR
2,53913,80,6,891,0,2244.67,891.0,0.0,891,891,...,0,0,0,0,0,0,0,0,0,nonTOR
3,53913,80,6,1074,0,1862.2,1074.0,0.0,1074,1074,...,0,0,0,0,0,0,0,0,0,nonTOR
4,53913,80,6,315,0,6349.21,315.0,0.0,315,315,...,0,0,0,0,0,0,0,0,0,nonTOR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67827,68,67,17,1,600000000,2000000,1.0,0.0,1,1,...,0,0,0,0,0,0,0,0,0,nonTOR
67828,34251,443,6,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67829,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67830,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR
67831,11365,443,6,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,nonTOR

In [11]:
SourcePortList = data[' Source Port']
DestinationPortList = data[' Destination Port']
ProtocolList = data[' Protocol']
FlowDurationList = data[' Flow Duration']
FlowIATMeanList = data[' Flow IAT Mean']
FlowIATStdList = data[' Flow IAT Std']
FlowIATMaxList = data[' Flow IAT Max']
FlowIATMinList = data[' Flow IAT Min']
BwdIATMinList = data[' Bwd IAT Min']
ActiveMeanList = data['Active Mean']
ActiveStdList = data[' Active Std']
ActiveMaxList = data[' Active Max']
ActiveMinList = data[' Active Min']
IdleMeanList = data['Idle Mean']
IdleStdList = data[' Idle Std']
IdleMaxList = data[' Idle Max']
IdleMinList = data[' Idle Min']

In [12]:
combinedList = list(zip(SourcePortList, DestinationPortList, ProtocolList, FlowDurationList, FlowIATMeanList, FlowIATStdList, FlowIATMaxList, FlowIATMinList, BwdIATMinList, ActiveMeanList, ActiveStdList, ActiveMaxList, ActiveMinList, IdleMeanList, IdleStdList, IdleMaxList, IdleMinList))

In [ ]:
combinedList

In [14]:
data['label'] = data['label'].map(lambda val : 0 if val == 'nonTor' else 1)

/home/bishal/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [15]:
data['label']

0        1
1        1
2        1
3        1
4        1
        ..
67827    1
67828    1
67829    1
67830    1
67831    1
Name: label, Length: 67832, dtype: int64

In [16]:
data

,Source Port,Destination Port,Protocol,Flow Duration,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,...,Bwd IAT Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,label
0,53913,80,6,435,0,4597.7,435.0,0.0,435,435,...,0,0,0,0,0,0,0,0,0,1
1,53913,80,6,259,0,7722.01,259.0,0.0,259,259,...,0,0,0,0,0,0,0,0,0,1
2,53913,80,6,891,0,2244.67,891.0,0.0,891,891,...,0,0,0,0,0,0,0,0,0,1
3,53913,80,6,1074,0,1862.2,1074.0,0.0,1074,1074,...,0,0,0,0,0,0,0,0,0,1
4,53913,80,6,315,0,6349.21,315.0,0.0,315,315,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67827,68,67,17,1,600000000,2000000,1.0,0.0,1,1,...,0,0,0,0,0,0,0,0,0,1
67828,34251,443,6,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,1
67829,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,1
67830,7116,1900,17,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,1
67831,11365,443,6,0,Infinity,Infinity,0.0,0.0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [17]:
target_value = list()

In [ ]:
for d in data['label']:
    target_value.append(d)

In [19]:
# target_value

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
random_state = 1
X = combinedList
y = target_value

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=random_state, stratify=y)

In [23]:
print("Number of training samples: {}".format(len(X_train)))
print("Number of testing samples: {}".format(len(X_test)))

Number of training samples: 54265
Number of testing samples: 13567

In [24]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

/home/bishal/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)

In [25]:
randomForest = RandomForestClassifier(max_depth=2, random_state=random_state)
decisionTree = DecisionTreeClassifier(random_state = random_state)

In [26]:
randomForest.fit(X_train, y_train)
print("Random Forest fitted")
decisionTree.fit(X_train, y_train)
print("Decision Tree fitted")

/home/bishal/anaconda3/lib/python3.7/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

Random Forest fitted
Decision Tree fitted

In [27]:
randomForestResult = randomForest.score(X_test, y_test)
decisionTreeResult = decisionTree.score(X_test, y_test)

In [28]:
print('Random Forest: {:.2f}'.format(randomForestResult))
print('Decision Tree: {:.2f}'.format(decisionTreeResult))

Random Forest: 1.00
Decision Tree: 1.00